# Generated by Django 5.2.16 on 2026-08-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
